from fpdf import FPDF
import os

def sanitize_text(text):
    """
    Removes or replaces all Unicode characters that break FPDF (latin-1).
    """
    if not isinstance(text, str):
        return str(text)

    replacements = {
        "•": "-",
        "–": "-",
        "—": "-",
        "’": "'",
        "“": '"',
        "”": '"',
        "❗": "!",
        "⚡": "*"
    }

    for k, v in replacements.items():
        text = text.replace(k, v)

    return text.encode("latin-1", "ignore").decode("latin-1")
def write_markdown_text(pdf, text, line_height=6):
    """
    Supports:
    - ### Headings → Bold + Larger
    - **bold** → Bold
    - Normal text → Regular
    """

    text = sanitize_text(text)

    lines = text.split("\n")

    for line in lines:
        line = line.strip()

        # ---------- HEADING SUPPORT: ### ----------
        if line.startswith("###"):
            heading = line.replace("###", "").strip()
            pdf.set_font("Arial", "B", 14)
            pdf.ln(2)
            pdf.multi_cell(0, line_height + 2, heading)
            pdf.ln(1)
            pdf.set_font("Arial", "", 11)
            continue

        # ---------- BOLD INLINE SUPPORT: ** ----------
        parts = line.split("**")
        is_bold = False

        pdf.set_x(pdf.l_margin)

        for part in parts:
            if is_bold:
                pdf.set_font("Arial", "B", 11)
            else:
                pdf.set_font("Arial", "", 11)

            pdf.write(line_height, part)
            is_bold = not is_bold

        pdf.ln(line_height)

    # Reset font after everything
    pdf.set_font("Arial", "", 11)


# ------------------ CONFIG ------------------
PAGE_W = 210  # A4 width in mm
PAGE_H = 297  # A4 height in mm
MARGIN_LR = 15

PRIMARY = (30, 64, 175)     # dark blue
ACCENT = (234, 179, 8)      # gold
TEXT_MAIN = (33, 37, 41)    # dark gray
TEXT_MUTED = (108, 117, 125)

# ✅ FONT PATH (UPDATE IF NEEDED)
DEJAVU_FONT_PATH = "/Users/shriyansh/Documents/dejavu-sans-ttf-2.37/ttf/DejaVuSans.ttf"


class ReportPDF(FPDF):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.set_auto_page_break(auto=True, margin=20)
        self.alias_nb_pages()

    # ----- HEADER -----
    def header(self):
        self.set_fill_color(*PRIMARY)
        self.rect(0, 0, PAGE_W, 18, "F")

        self.set_y(5)
        self.set_x(MARGIN_LR)
        self.set_text_color(255, 255, 255)
        self.set_font("Arial", "B", 16)
        self.cell(0, 8, "Squat Pose Analysis Report", ln=1)

        self.set_font("Arial", "", 10)
        self.set_text_color(225, 225, 225)
        self.set_x(MARGIN_LR)
        self.cell(0, 6, "Human Pose Estimation Automated Form Analysis", ln=1)

        self.set_y(22)

    # ----- FOOTER -----
    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(*TEXT_MUTED)
        self.cell(0, 5, "Generated by Human Pose Analyzer", 0, 1, "C")
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", 0, 0, "C")

    # ----- HELPERS -----
    def section_title(self, text):
        self.ln(5)
        self.set_font("Arial", "B", 13)
        self.set_text_color(*PRIMARY)
        self.cell(0, 8, text, ln=1)
        y = self.get_y()
        self.set_draw_color(*ACCENT)
        self.set_line_width(0.6)
        self.line(MARGIN_LR, y, PAGE_W - MARGIN_LR, y)
        self.ln(3)
        self.set_text_color(*TEXT_MAIN)

    def section_subtitle(self, text):
        self.set_font("Arial", "I", 10)
        self.set_text_color(*TEXT_MUTED)
        self.cell(0, 6, text, ln=1)
        self.set_text_color(*TEXT_MAIN)

    def key_value_row(self, label, value):
        self.set_font("Arial", "", 11)
        self.set_text_color(*TEXT_MUTED)
        self.cell(45, 6, label, 0, 0)
        self.set_text_color(*TEXT_MAIN)
        self.cell(0, 6, value, 0, 1)

    def two_column_images_with_captions(self, items, img_width=80):
        col_width = (PAGE_W - 2 * MARGIN_LR) / 2
        x = MARGIN_LR
        y = self.get_y()

        for i, (label, imgpath) in enumerate(items):
            self.set_xy(x, y)
            self.set_font("Arial", "B", 10)
            self.multi_cell(col_width, 5, label)
            y_img = self.get_y() + 2
            self.set_xy(x, y_img)
            self.image(imgpath, w=img_width)

            if i % 2 == 0:
                x = MARGIN_LR + col_width
            else:
                x = MARGIN_LR
                y = y_img + img_width * 0.75 + 8

        self.set_y(y + 5)


# ✅ ✅ MAIN FUNCTION CALLED FROM squat.py
def save_full_report_and_video(
    reps,
    session_time,
    avg_depth,
    fastest,
    slowest,
    std_depth,
    chat_response,
    key_frames_paths,
    score,
    flags,
    angle_plot_path,
    rep_dur_plot_path,
    heatmap_path,
    output_dir,
):
    os.makedirs(output_dir, exist_ok=True)

    pdf = ReportPDF()
    pdf.add_page()

    # ✅ Unicode font
    if os.path.exists(DEJAVU_FONT_PATH):
        pdf.add_font("DejaVu", "", DEJAVU_FONT_PATH, uni=True)

    # -------- SUMMARY --------
    pdf.section_title("Summary")
    pdf.section_subtitle("Session overview")

    pdf.key_value_row("Total repetitions", str(len(reps)))
    pdf.key_value_row("Session duration", f"{session_time:.2f} sec")
    pdf.key_value_row("Average squat depth", f"{avg_depth:.1f}°")
    pdf.key_value_row("Fastest / slowest rep", f"{fastest:.2f}s / {slowest:.2f}s")
    pdf.key_value_row("Depth consistency (std)", f"{std_depth:.2f}")

    # -------- EXPERT FEEDBACK --------
    pdf.section_title("Expert Feedback")
    pdf.section_subtitle("Automatic coaching suggestions")
    pdf.set_font("DejaVu" if os.path.exists(DEJAVU_FONT_PATH) else "Arial", "", 11)
    write_markdown_text(pdf, chat_response, line_height=6)

    # -------- REP TABLE --------
    pdf.section_title("Rep-by-Rep Performance")

    if reps:
        headers = ["Rep", "Start", "End", "Min angle", "Dur (s)", "Status"]
        colw = (PAGE_W - 2 * MARGIN_LR) / len(headers)

        # ----- HEADER ROW -----
        pdf.set_font("Arial", "B", 10)
        pdf.set_fill_color(0, 0, 0)
        pdf.set_text_color(255, 255, 255)

        for h in headers:
            pdf.cell(colw, 8, h, 1, 0, "C", True)
        pdf.ln()

        # Reset for rows
        pdf.set_text_color(*TEXT_MAIN)
        pdf.set_font("Arial", "", 9)

        # ----- DATA ROWS -----
        for i, rep in enumerate(reps):

            issues = []

            # ❌ Depth check (not deep enough)
            if rep["min_angle"] > 90:
                issues.append("Shallow")

            # ❌ Speed check (too fast)
            if rep["duration"] < 0.5:
                issues.append("Too Fast")

            # ✅ Final status text
            if issues:
                status = ", ".join(issues)
            else:
                status = "Correct"

            pdf.cell(colw, 7, str(i + 1), 1, 0, "C")
            pdf.cell(colw, 7, str(rep["start"]), 1, 0, "C")
            pdf.cell(colw, 7, str(rep["end"]), 1, 0, "C")
            pdf.cell(colw, 7, f"{rep['min_angle']:.1f}", 1, 0, "R")
            pdf.cell(colw, 7, f"{rep['duration']:.2f}", 1, 0, "R")
            pdf.cell(colw, 7, status, 1, 1, "C")

    # -------- VISUALIZATIONS --------
    pdf.section_title("Visualizations")

    full_width = PAGE_W - 2 * MARGIN_LR
    center_x = (PAGE_W - full_width) / 2

    # 1️⃣ Angle progression plot (centered)
    pdf.image(angle_plot_path, x=center_x, w=full_width)
    pdf.ln(6)

    # 2️⃣ Rep duration plot (centered)
    pdf.image(rep_dur_plot_path, x=center_x, w=full_width)
    pdf.ln(6)

    # 3️⃣ Heatmap plot (centered)
    pdf.image(heatmap_path, x=center_x, w=full_width)
    pdf.ln(6)


    # -------- KEY FRAMES --------
    pdf.section_title("Key Frames")

    key_items = [(label, imgpath) for label, imgpath in key_frames_paths.items()]

    if key_items:
        # ✅ Force new page for safety (prevents footer overlap)
        pdf.add_page()

        col_width = (PAGE_W - 2 * MARGIN_LR) / 3
        img_height = 85   # ✅ Fixed equal height for all images
        y_start = pdf.get_y() + 8

        x_positions = [
            MARGIN_LR,
            MARGIN_LR + col_width,
            MARGIN_LR + 2 * col_width,
        ]
        
        # ✅ Draw titles centered above each image
        for i, (label, _) in enumerate(key_items):
            pdf.set_xy(x_positions[i], y_start)
            pdf.set_font("Arial", "B", 11)
            pdf.cell(col_width, 6, label, align="C")

        y_images = y_start + 8

        # ✅ Draw images with SAME HEIGHT and SAFE WIDTH
        for i, (_, imgpath) in enumerate(key_items):
            pdf.image(
                imgpath,
                x=x_positions[i] + 5,
                y=y_images,
                w=col_width - 10,
                h=img_height,
            )

        # ✅ Move cursor BELOW all images safely so nothing overlaps
        pdf.set_y(y_images + img_height + 12)


    # -------- QUALITY --------
    pdf.section_title("Quality Assessment")
    pdf.cell(0, 7, f"Depth score: {score}%", ln=1)
    pdf.set_font("DejaVu" if os.path.exists(DEJAVU_FONT_PATH) else "Arial", "", 11)
    if flags:
        for f in flags:
            safe_text = sanitize_text(f"- {f}")
            pdf.multi_cell(0, 6, safe_text)
    else:
        pdf.multi_cell(0, 6, "No major form issues detected. Great job!")

    # -------- TIMING --------
    pdf.section_title("Timing Information")
    pdf.key_value_row("Total exercise time", f"{session_time:.2f} sec")
    pdf.key_value_row(
        "Average rep time",
        f"{sum([r['duration'] for r in reps]) / len(reps):.2f} sec" if reps else "N/A",
    )
    pdf.key_value_row("Fastest rep", f"{fastest:.2f} sec")
    pdf.key_value_row("Slowest rep", f"{slowest:.2f} sec")

    # -------- SAVE --------
    pdf_path = os.path.join(output_dir, "squat_pose_report_pro.pdf")
    pdf.output(pdf_path)

    return pdf_path
